
import { Book, CategoryInfo } from './types';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Số Đỏ (Dumb Luck)',
    author: 'Vũ Trọng Phụng',
    authorBio: 'Vũ Trọng Phụng (1912–1939) là một nhà văn, nhà báo nổi tiếng của Việt Nam đầu thế kỷ 20. Ông được mệnh danh là "ông vua phóng sự đất Bắc".',
    price: 155000,
    stock_quantity: 15,
    rating: 4.9,
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=800&auto=format&fit=crop',
    category: 'Văn học',
    description: 'Một kiệt tác trào phúng của văn học Việt Nam hiện đại, phơi bày sự lố lăng của xã hội tư sản thành thị thời Pháp thuộc thông qua cuộc đời của Xuân Tóc Đỏ.',
    isbn: '978-604-335-012-4',
    pages: 256,
    publisher: 'NXB Hội Nhà Văn',
    publishYear: 2021,
    language: 'Tiếng Việt',
    badge: 'Kinh Điển'
  },
  {
    id: '2',
    title: 'Cho Tôi Xin Một Vé Đi Tuổi Thơ',
    author: 'Nguyễn Nhật Ánh',
    authorBio: 'Nguyễn Nhật Ánh là một trong những nhà văn thành công nhất Việt Nam chuyên viết cho tuổi mới lớn.',
    price: 120000,
    stock_quantity: 20,
    rating: 4.8,
    cover: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=800&auto=format&fit=crop',
    category: 'Văn học',
    description: 'Cuốn sách đưa người đọc trở về với những kỷ niệm trong sáng, hồn nhiên của thời thơ ấu.',
    isbn: '978-604-2-12345-6',
    pages: 212,
    publisher: 'NXB Trẻ',
    publishYear: 2022,
    language: 'Tiếng Việt',
    badge: 'Bán Chạy'
  },
  {
    id: '3',
    title: 'Nỗi Buồn Chiến Tranh',
    author: 'Bảo Ninh',
    authorBio: 'Bảo Ninh là một nhà văn quân đội tài năng. Tác phẩm của ông mang tầm vóc quốc tế.',
    price: 189000,
    stock_quantity: 8,
    rating: 4.9,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop',
    category: 'Văn học',
    description: 'Khắc họa những nỗi đau âm ỉ và thân phận con người sau cuộc chiến Việt Nam.',
    isbn: '978-604-1-67890-1',
    pages: 310,
    publisher: 'NXB Trẻ',
    publishYear: 2018,
    language: 'Tiếng Việt',
    badge: 'Giải Thưởng'
  },
  {
    id: '4',
    title: 'Atomic Habits',
    author: 'James Clear',
    authorBio: 'James Clear là chuyên gia hàng đầu thế giới về hình thành thói quen.',
    price: 195000,
    stock_quantity: 25,
    rating: 4.9,
    cover: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=800&auto=format&fit=crop',
    category: 'Kỹ năng',
    description: 'Cách cực kỳ đơn giản để hình thành thói quen tốt và loại bỏ thói quen xấu qua những thay đổi nhỏ.',
    isbn: '978-0-7352-1129-2',
    pages: 320,
    publisher: 'Penguin Random House',
    publishYear: 2018,
    language: 'Tiếng Anh',
    badge: 'Gợi Ý'
  },
  {
    id: '5',
    title: 'Dế Mèn Phiêu Lưu Ký',
    author: 'Tô Hoài',
    authorBio: 'Tô Hoài (1920–2014) là một trong những tên tuổi lớn nhất của văn học hiện đại Việt Nam.',
    price: 99000,
    stock_quantity: 12,
    rating: 4.6,
    cover: 'https://images.unsplash.com/photo-1543004218-ee141104623a?q=80&w=800&auto=format&fit=crop',
    category: 'Thiếu nhi',
    description: 'Tác phẩm thiếu nhi kể về hành trình phiêu lưu tự do của chú Dế Mèn dũng cảm.',
    isbn: '978-604-2-00456-7',
    pages: 148,
    publisher: 'NXB Kim Đồng',
    publishYear: 2020,
    language: 'Tiếng Việt',
    badge: 'Thiếu Nhi'
  },
  {
    id: '6',
    title: 'Muôn Kiếp Nhân Sinh',
    author: 'Nguyên Phong',
    authorBio: 'Nguyên Phong (GS. John Vũ) là nhà khoa học tại Boeing và tác giả tâm linh nổi tiếng.',
    price: 220000,
    stock_quantity: 18,
    rating: 4.9,
    cover: 'https://images.unsplash.com/photo-1511108690759-009324a90311?q=80&w=800&auto=format&fit=crop',
    category: 'Kỹ năng',
    description: 'Cái nhìn sâu sắc về quy luật nhân quả, luân hồi qua những câu chuyện tiền kiếp.',
    isbn: '978-604-331-155-2',
    pages: 420,
    publisher: 'First News - Trí Việt',
    publishYear: 2020,
    language: 'Tiếng Việt',
    badge: 'Hot'
  },
  {
    id: '7',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    authorBio: 'Morgan Housel là chuyên gia nghiên cứu về hành vi tài chính con người.',
    price: 180000,
    stock_quantity: 14,
    rating: 4.6,
    cover: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?q=80&w=800&auto=format&fit=crop',
    category: 'Kinh tế',
    description: 'Quản lý tiền bạc không hẳn là những gì bạn biết. Đó là cách bạn hành động.',
    isbn: '978-0-85719-768-9',
    pages: 252,
    publisher: 'Harriman House',
    publishYear: 2020,
    language: 'Tiếng Anh'
  },
  {
    id: '8',
    title: 'Nhà Giả Kim',
    author: 'Paulo Coelho',
    authorBio: 'Paulo Coelho là tiểu thuyết gia người Brazil nổi tiếng nhất thế giới.',
    price: 130000,
    stock_quantity: 30,
    rating: 4.8,
    cover: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?q=80&w=800&auto=format&fit=crop',
    category: 'Văn học',
    description: 'Hành trình đi tìm vận mệnh của chàng chăn cừu Santiago đầy cảm hứng.',
    isbn: '978-0-06-231500-7',
    pages: 180,
    publisher: 'HarperOne',
    publishYear: 1988,
    language: 'Tiếng Việt'
  },
  {
    id: '9',
    title: 'Việt Nam Sử Lược',
    author: 'Trần Trọng Kim',
    authorBio: 'Học giả Trần Trọng Kim là người hệ thống lịch sử Việt Nam hiện đại.',
    price: 250000,
    stock_quantity: 5,
    rating: 4.8,
    cover: 'https://images.unsplash.com/photo-1592492159418-39f319320569?q=80&w=800&auto=format&fit=crop',
    category: 'Lịch sử',
    description: 'Bộ sử chính thống, khoa học về toàn bộ tiến trình lịch sử Việt Nam.',
    isbn: '978-604-9-12378-0',
    pages: 600,
    publisher: 'NXB Văn Học',
    publishYear: 2019,
    language: 'Tiếng Việt',
    badge: 'Lịch Sử'
  },
  {
    id: '10',
    title: 'Đắc Nhân Tâm',
    author: 'Dale Carnegie',
    authorBio: 'Dale Carnegie là người tiên phong phát triển các kỹ năng giao tiếp.',
    price: 115000,
    stock_quantity: 22,
    rating: 4.7,
    cover: 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?q=80&w=800&auto=format&fit=crop',
    category: 'Kỹ năng',
    description: 'Cuốn sách nghệ thuật ứng xử hay nhất mọi thời đại.',
    isbn: '978-0-671-02703-2',
    pages: 290,
    publisher: 'Simon & Schuster',
    publishYear: 2015,
    language: 'Tiếng Việt',
    badge: 'Kinh Điển'
  },
  {
    id: '11',
    title: 'Deep Work',
    author: 'Cal Newport',
    authorBio: 'Cal Newport là giáo sư khoa học máy tính và chuyên gia về năng suất tập trung.',
    price: 175000,
    stock_quantity: 9,
    rating: 4.8,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop',
    category: 'Kinh tế',
    description: 'Tập trung cao độ trong một thế giới đầy xao nhãng để đạt được hiệu quả vượt trội.',
    isbn: '978-1455586691',
    pages: 304,
    publisher: 'Grand Central Publishing',
    publishYear: 2016,
    language: 'Tiếng Anh',
    badge: 'Khuyên Đọc'
  },
  {
    id: '12',
    title: 'Cánh Đồng Bất Tận',
    author: 'Nguyễn Ngọc Tư',
    authorBio: 'Nguyễn Ngọc Tư là nhà văn nữ tiêu biểu của văn học đương đại Việt Nam.',
    price: 105000,
    stock_quantity: 7,
    rating: 4.7,
    cover: 'https://images.unsplash.com/photo-1491843384429-17e71289ff39?q=80&w=800&auto=format&fit=crop',
    category: 'Văn học',
    description: 'Những câu chuyện đượm buồn về thân phận con người miền sông nước.',
    isbn: '978-604-3-00012-3',
    pages: 218,
    publisher: 'NXB Trẻ',
    publishYear: 2019,
    language: 'Tiếng Việt',
    badge: 'Đặc Sắc'
  }
];

export const CATEGORIES: CategoryInfo[] = [
  { name: 'Tất cả sách', icon: 'fa-book-open', description: 'Tất cả bộ sưu tập tinh hoa.' },
  { name: 'Văn học', icon: 'fa-hat-wizard', description: 'Thế giới của những điều tưởng tượng.' },
  { name: 'Kỹ năng', icon: 'fa-brain', description: 'Tri thức thực tế và phát triển bản thân.' },
  { name: 'Kinh tế', icon: 'fa-chart-line', description: 'Kinh doanh, đầu tư và tài chính.' },
  { name: 'Lịch sử', icon: 'fa-landmark', description: 'Tìm về nguồn cội và những dấu mốc.' },
  { name: 'Thiếu nhi', icon: 'fa-child', description: 'Những trang sách nuôi dưỡng tâm hồn trẻ thơ.' }
];
